src/Entity/Habitat.php
<?php

namespace App\Entity;

use App\Repository\HabitatRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;

#[ORM\Entity(repositoryClass: HabitatRepository::class)]
class Habitat
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $name = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $descript = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $img = null;

    #[ORM\OneToMany(mappedBy: 'habitat', targetEntity: Animal::class)]
    private Collection $animals;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $comment_habitat = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getDescript(): ?string
    {
        return $this->descript;
    }

    public function setDescript(?string $descript): static
    {
        $this->descript = $descript;

        return $this;
    }

    public function getImg(): ?string
    {
        return $this->img;
    }

    public function setImg(?string $img): static
    {
        $this->img = $img;

        return $this;
    }

    public function getCommentHabitat(): ?string
    {
        return $this->comment_habitat;
    }

    public function setCommentHabitat(?string $comment_habitat): static
    {
        $this->comment_habitat = $comment_habitat;

        return $this;
    }

      /**
     * @return Collection<int, Animal>
     */
    public function getAnimals(): Collection
    {
        return $this->animals;
    }

    public function addAnimal(Animal $animal): self
    {
        if (!$this->animals->contains($animal)) {
            $this->animals->add($animal);
            $animal->setHabitat($this);
        }

        return $this;
    }

    public function removeAnimal(Animal $animal): self
    {
        if ($this->animals->removeElement($animal)) {
            // set the owning side to null (unless already changed)
            if ($animal->getHabitat() === $this) {
                $animal->setHabitat(null);
            }
        }

        return $this;
    }
}

src/Form/HabitatType.php
<?php

namespace App\Form;

use App\Entity\Habitat;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class HabitatType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name')
            ->add('descript')
            ->add('img')
            ->add('comment_habitat')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Habitat::class,
        ]);
    }
}

src/Controller/HabitatController.php
<?php

namespace App\Controller;

use App\Entity\Habitat;
use App\Form\HabitatType;
use App\Repository\HabitatRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/habitat')]
final class HabitatController extends AbstractController
{
    #[Route(name: 'app_habitat_index', methods: ['GET'])]
    public function index(HabitatRepository $habitatRepository): Response
    {
        return $this->render('habitat/index.html.twig', [
            'habitats' => $habitatRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_habitat_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $habitat = new Habitat();
        $form = $this->createForm(HabitatType::class, $habitat);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($habitat);
            $entityManager->flush();

            return $this->redirectToRoute('app_habitat_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('habitat/new.html.twig', [
            'habitat' => $habitat,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_habitat_show', methods: ['GET'])]
    public function show(Habitat $habitat): Response
    {
        return $this->render('habitat/show.html.twig', [
            'habitat' => $habitat,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_habitat_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Habitat $habitat, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(HabitatType::class, $habitat);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_habitat_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('habitat/edit.html.twig', [
            'habitat' => $habitat,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_habitat_delete', methods: ['POST'])]
    public function delete(Request $request, Habitat $habitat, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$habitat->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($habitat);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_habitat_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/habitat/_delete_form.html.twig
<form method="post" action="{{ path('app_habitat_delete', {'id': habitat.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ habitat.id) }}">
    <button class="btn">Delete</button>
</form>

templates/habitat/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/habitat/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Habitat{% endblock %}

{% block body %}
    <h1>Edit Habitat</h1>

    {{ include('habitat/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_habitat_index') }}">back to list</a>

    {{ include('habitat/_delete_form.html.twig') }}
{% endblock %}

templates/habitat/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Habitat index{% endblock %}

{% block body %}
    <h1>Habitat index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Descript</th>
                <th>Img</th>
                <th>Comment_habitat</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for habitat in habitats %}
            <tr>
                <td>{{ habitat.id }}</td>
                <td>{{ habitat.name }}</td>
                <td>{{ habitat.descript }}</td>
                <td>{{ habitat.img }}</td>
                <td>{{ habitat.commentHabitat }}</td>
                <td>
                    <a href="{{ path('app_habitat_show', {'id': habitat.id}) }}">show</a>
                    <a href="{{ path('app_habitat_edit', {'id': habitat.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_habitat_new') }}">Create new</a>
{% endblock %}

templates/habitat/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Habitat{% endblock %}

{% block body %}
    <h1>Create new Habitat</h1>

    {{ include('habitat/_form.html.twig') }}

    <a href="{{ path('app_habitat_index') }}">back to list</a>
{% endblock %}

templates/habitat/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Habitat{% endblock %}

{% block body %}
    <h1>Habitat</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ habitat.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ habitat.name }}</td>
            </tr>
            <tr>
                <th>Descript</th>
                <td>{{ habitat.descript }}</td>
            </tr>
            <tr>
                <th>Img</th>
                <td>{{ habitat.img }}</td>
            </tr>
            <tr>
                <th>Comment_habitat</th>
                <td>{{ habitat.commentHabitat }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_habitat_index') }}">back to list</a>

    <a href="{{ path('app_habitat_edit', {'id': habitat.id}) }}">edit</a>

    {{ include('habitat/_delete_form.html.twig') }}
{% endblock %}